on: [push, pull_request]
name: build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Haskell
        uses: actions/setup-haskell@v1.1
      - name: deps
        run: cabal install random
      - name: build
        run: make
